name: example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Mali
      fonts:
        - asset: fonts/Mali-SemiBold.ttf
        - asset: fonts/Mali-Regular.ttf
        - asset: fonts/Mali-Medium.ttf
        - asset: fonts/Mali-Light.ttf
        - asset: fonts/Mali-ExtraLight.ttf
        - asset: fonts/Mali-Bold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
    - family: Inter
      fonts: 
        - asset: fonts/Inter-Black.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf      
